title: Jay Patil
author: Jay Patil
url: "https://JayPatil9.github.io"

markdown: kramdown
highlighter: rouge
theme_config:
  appearance: "auto"

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex